# Generated by Django 3.1.3 on 2021-04-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('meassure', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
                ('components', models.ManyToManyField(related_name='food', to='core.Component')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.componentgroup')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componenttype'),
        ),
    ]
