# Generated by Django 3.1.3 on 2021-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('enable', models.BooleanField(default=True)),
                ('lens', models.IntegerField(blank=True, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('blade_length_x', models.IntegerField(default=0)),
                ('blade_length_y', models.IntegerField(default=0)),
                ('ground_elevation', models.IntegerField(default=0)),
            ],
        ),
    ]
