# Generated by Django 3.1.3 on 2021-04-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('meassure', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
                ('components', models.ManyToManyField(to='core.Component')),
            ],
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_description', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.AddField(
            model_name='food',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foodgroup'),
        ),
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componentgroup'),
        ),
    ]
